# Generated by Django 4.1.3 on 2023-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raspisanie_Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('raspisanie_bus', models.FileField(upload_to='raspisanie_bus/%Y/%m/%d/', verbose_name='Файл с расписанием автобуса')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Расписание автобуса',
                'verbose_name_plural': 'Расписание автобуса',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='raspisanie_new',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='raspisanie_post',
            name='raspisanie_post_6saturday',
            field=models.FileField(blank=True, upload_to='raspisanie_post/%Y/6saturday/', verbose_name='Файл с расписанием на субботу'),
        ),
        migrations.AlterField(
            model_name='raspisanie_post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
